{% set name = "xmlsec" %}
{% set version = "1.3.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 934f804f2f895bcdb86f1eaee236b661013560ee69ec108d29cdd6e5f292a2d9

build:
  number: 0
  # Skip s390x because of missing libxmlsec1, libgpg-error and libgcrypt
  skip: true  # [(linux and s390x) or win or py<35]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
  host:
    - python
    - libxml2 {{ libxml2 }}
    - libxmlsec1 1.3.5
    - lxml 5.2.1
    - pip
    - pkgconfig
    - setuptools
    - setuptools_scm
    - toml
    - wheel
  run:
    - python
    - lxml >=3.8.0

test:
  imports:
    - xmlsec
  requires:
    - pip
  commands:
    - pip check
    # Check that the correct version is reported by pip
    - "pip list --format json | grep '{\"name\": \"xmlsec\", \"version\": \"{{ version }}\"}'"

about:
  home: https://github.com/mehcode/python-xmlsec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bindings for the XML Security Library (XMLSec).
  description: |
    Python bindings for the XML Security Library (XMLSec).
  doc_url: https://xmlsec.readthedocs.io/
  dev_url: https://github.com/mehcode/python-xmlsec
